### Get all Account
GET http://localhost:3000/api/v1/account
Authorization: "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjdWlkIjoiY2x0NWMwa3Q1MDAwMGlsdHNmdHU1MDIxeSIsIm5hbWUiOiJQYW5qaSBQdXNha2EiLCJlbWFpbCI6ImdhbWVjZW50ZXIxOTIwQGdtYWlsLmNvbSIsImlhdCI6MTcwOTA5NjY0N30.n_RgTKQffk9wgCGy0YemZFA8FswX_U-BH17zxGkZejQ"

### Create Account
POST http://localhost:3000/api/v1/account
Authorization: "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjdWlkIjoiY2x0NWMwa3Q1MDAwMGlsdHNmdHU1MDIxeSIsIm5hbWUiOiJQYW5qaSBQdXNha2EiLCJlbWFpbCI6ImdhbWVjZW50ZXIxOTIwQGdtYWlsLmNvbSIsImlhdCI6MTcwOTA5NjY0N30.n_RgTKQffk9wgCGy0YemZFA8FswX_U-BH17zxGkZejQ"

{
    "name": "Weekly Spend Combat",
    "balance": 1000000
}

### Get single Account
GET http://localhost:3000/api/v1/account/clt7c9npj000ae6kjgm520mzk
Authorization: "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjdWlkIjoiY2x0NWMwa3Q1MDAwMGlsdHNmdHU1MDIxeSIsIm5hbWUiOiJQYW5qaSBQdXNha2EiLCJlbWFpbCI6ImdhbWVjZW50ZXIxOTIwQGdtYWlsLmNvbSIsImlhdCI6MTcwOTA5NjY0N30.n_RgTKQffk9wgCGy0YemZFA8FswX_U-BH17zxGkZejQ"

### Delete Account
DELETE http://localhost:3000/api/v1/account/clt8hu23200037ijx8hdfqpai
Authorization: "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjdWlkIjoiY2x0NWMwa3Q1MDAwMGlsdHNmdHU1MDIxeSIsIm5hbWUiOiJQYW5qaSBQdXNha2EiLCJlbWFpbCI6ImdhbWVjZW50ZXIxOTIwQGdtYWlsLmNvbSIsImlhdCI6MTcwOTA5NjY0N30.n_RgTKQffk9wgCGy0YemZFA8FswX_U-BH17zxGkZejQ"

### Update Account
PATCH http://localhost:3000/api/v1/account/clt7c9npj000ae6kjgm520mzk
Authorization: "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjdWlkIjoiY2x0NWMwa3Q1MDAwMGlsdHNmdHU1MDIxeSIsIm5hbWUiOiJQYW5qaSBQdXNha2EiLCJlbWFpbCI6ImdhbWVjZW50ZXIxOTIwQGdtYWlsLmNvbSIsImlhdCI6MTcwOTA5NjY0N30.n_RgTKQffk9wgCGy0YemZFA8FswX_U-BH17zxGkZejQ"

{
    "balance": 120000
}